/* GENERATED by scripts/build-mark.mjs. Do not hand-edit — re-run the script.

   SECTION 9 OF docs/specs/logo.md IS THE STORE OF RECORD FOR EVERY HEX BELOW, and
   `make docs-audit`'s `logo parity` row reconciles this file against it in both directions.
   These are NOT derived here: the ground rule, applied to the three gold prisms, produces the
   espresso that section 8 rejected in favor of true black, so a build that re-derives them
   redraws marks the spec has eliminated.

   THIS IS THE ONE FILE IN app/ OUTSIDE tokens.css THAT MAY NAME A COLOR (D102). The mark is an
   illustration with a palette locked by another document, not part of the product's semantic
   palette, and it must not be theme-overridable — which is exactly what putting it in
   tokens.css would invite. */

export type LogoVariant = 'bluesteel' | 'lilacish' | 'mint' | 'yellowGold' | 'whiteGold' | 'roseGold'

/** Section 9's default: "the one `Logo` and `favicon.svg` take when nothing else is specified".
 *  The other five are the set, not alternates to it. */
export const DEFAULT_VARIANT: LogoVariant = 'bluesteel'

export interface MarkPalette {
  readonly label: string
  readonly prism: readonly [string, string, string, string, string]
  readonly bracket: readonly [string, string, string, string]
  readonly ground: readonly [string, string]
  readonly base: string
}

/** Sheen 0.15 on all six — section 9, inside section 3's settled 0.10-0.20 band. */
export const SHEEN = 0.15

export const MARKS: Readonly<Record<LogoVariant, MarkPalette>> = {
  bluesteel: {
    label: 'bluesteel',
    prism: ['#E4EEF8', '#B0C8E0', '#7F9FC0', '#F2F8FF', '#6086AC'],
    bracket: ['#FFFFFF', '#B8C8D8', '#F2F8FF', '#8FA4B8'],
    ground: ['#182430', '#060B12'],
    base: '#5A6E80',
  },
  lilacish: {
    label: 'lilacish',
    prism: ['#EFEAFA', '#BCB4E0', '#8E86C0', '#F6F2FF', '#6E68A8'],
    bracket: ['#FFFFFF', '#B8C8D8', '#F2F8FF', '#8FA4B8'],
    ground: ['#231F34', '#0B0914'],
    base: '#5A6E80',
  },
  mint: {
    label: 'mint',
    prism: ['#E6F6F0', '#A8D4C4', '#78AC9C', '#F2FCF8', '#589084'],
    bracket: ['#FFFFFF', '#B8C8D8', '#F2F8FF', '#8FA4B8'],
    ground: ['#162722', '#050D0A'],
    base: '#5A6E80',
  },
  yellowGold: {
    label: 'yellow gold',
    prism: ['#FFD97A', '#F0A82E', '#C9821E', '#FFEFC0', '#B36F18'],
    bracket: ['#FFFBEE', '#E8CE8A', '#FFFDF6', '#C0A254'],
    ground: ['#141619', '#000000'],
    base: '#C98A2E',
  },
  whiteGold: {
    label: 'white gold',
    prism: ['#FFFBF2', '#EFE6D2', '#DCD0B8', '#FFFFFF', '#C9BCA2'],
    bracket: ['#FFFBEE', '#E8CE8A', '#FFFDF6', '#C0A254'],
    ground: ['#141619', '#000000'],
    base: '#D8D2C4',
  },
  roseGold: {
    label: 'rose gold',
    prism: ['#FFD9C8', '#F0B49A', '#DE9070', '#FFE9DF', '#C87A5C'],
    bracket: ['#FFF0E8', '#E8B49C', '#FFF8F4', '#C88A6C'],
    ground: ['#141619', '#000000'],
    base: '#D99878',
  },
}

export const VARIANTS = Object.keys(MARKS) as readonly LogoVariant[]
