import { useId } from 'react'

import { SMALL_BRACKET, SMALL_STROKE } from './markGeometry'
import { MARKS } from './markPalettes'

/* THE EMPTY SLOT — the mark's brackets with the card taken out.
 *
 * docs/specs/logo.md section 1 names this rather than describing it: "with the card removed the
 * same brackets become an empty slot, which is the in-product mark". The collapsed sidebar is
 * where that reading is literal — the lockup is the name inside its address, and the rail is the
 * address with the name taken out of it. The full tile mark shipped in that slot until now, and
 * it read as the favicon rather than as the collapsed lockup.
 *
 * NOTHING HERE IS DRAWN. `SMALL_BRACKET` and `SMALL_STROKE` come from `markGeometry.ts`,
 * generated by `scripts/build-mark.mjs`, so this is the same wire `Logo` strokes below 64px — the
 * same path and the same weight. It is the mark with two elements omitted, not a second drawing
 * of it, and `make docs-audit`'s `rail mark` row holds it to that.
 *
 * NO TILE AND NO CARD, so it carries no ground and inherits the surface it sits on. That is what
 * lets ONE drawing sit in a light sidebar and a dark one; `Logo` cannot, because section 12 fixed
 * its tile dark in both themes after a light ground lost the silhouette at every size this app
 * draws. Having no ground is also why the chrome cannot simply be painted on: `bluesteel`'s four
 * bracket stops run #FFFFFF to #8FA4B8, which is a bright wire on the dark tile and an invisible
 * one on a light sidebar. So this takes SECTION 16's switch, the lockup's own — flat `--bn-ink`
 * on light, the chrome on dark — and `kit.css` decides, because the gradient's id is a `useId()`
 * a stylesheet cannot name.
 *
 * `aria-hidden`, always, exactly as `Logo` is: every call site names its own wrapper. */
export function RailMark({
  size = 32,
  className,
}: {
  readonly size?: number
  readonly className?: string
}) {
  // per instance — the sidebar and a crash page can be mounted at once, and two marks sharing
  // `url(#b)` is silent: both references resolve, to the first one's gradient
  const id = useId().replace(/:/g, '')

  const arm = (
    <path
      className="bn-rail-mark-arm"
      d={SMALL_BRACKET}
      fill="none"
      strokeWidth={SMALL_STROKE}
      strokeLinecap="round"
    />
  )

  return (
    <svg
      className={className ? `bn-rail-mark ${className}` : 'bn-rail-mark'}
      width={size}
      height={size}
      viewBox="0 0 100 100"
      // read by kit.css, which chooses between this and flat ink per theme — the same contract
      // `Lockup` publishes, on `stroke` rather than `fill` because this cut is a wire
      style={{ ['--bn-lockup-metal' as string]: `url(#${id}b)` }}
      aria-hidden="true"
    >
      <defs>
        <linearGradient id={`${id}b`} x1=".75" y1=".067" x2=".25" y2=".933">
          {MARKS.bluesteel.bracket.map((c, i) => (
            <stop key={c + i} offset={[0, 0.33, 0.67, 1][i]} stopColor={c} />
          ))}
        </linearGradient>
      </defs>
      {arm}
      <g transform="rotate(180 50 50)">{arm}</g>
    </svg>
  )
}
