"""T8 — The code-card track: QR decode, the product tier, the ledger, and the seam.

NEW 2026-08-30, with C9-C11. It exists as its own failing test name for the reason every
other one does: a code is a BEARER INSTRUMENT sold to a stranger, and the three ways this
track can lose money are three different failures that must not hide inside one another.

    a WRONG code                 the buyer gets something that does not work, finds out
                                 days later, and nobody can tell whether the code was bad
                                 or the read was. Checked below by round-tripping every
                                 decode against the string that was encoded.
    a code sold TWICE            unrecoverable (C3). Checked by driving the reservation
                                 into every state that must refuse it.
    a PREMIUM code in a bulk lot a Pokemon Center ETB code lists at ~46x a booster, so this
                                 is the quiet one — it costs real money and leaves no trace.
                                 Checked by asserting the lanes exclude what they must.

SYNTHETIC QR SYMBOLS, GENERATED BY THE DECODER'S OWN ENCODER. `zxing-cpp` both writes and
reads, so this test needs no dependency `codes/qr.py` does not already have — and, more to
the point, no real code-card photograph. One may never live in this repo: the opsec rules
are absolute about it, and a test fixture is a tracked file.

WHAT A GREEN T8 DOES NOT MEAN. It does not mean the decoder works on a real card. Every
frame here is drawn by this test from the physical card's geometry, so the answer key is
exact and the picture is one this test already knows how to read — exactly T6's blind spot,
in the same words, and `docs/specs/code-cards.md` §8 keeps it as the open question it is.
No real code card has ever been through this pipeline.
"""

from __future__ import annotations

import json
import random
import tempfile
from pathlib import Path

from harness.tests import Checks, Result

NAME = "T8"
DESCRIPTION = "Code cards: QR decode, product tier, ledger, and the channel seam"
PASS_CRITERIA = (
    "every decode round-trips its own code with zero mis-reads; an unreadable frame refuses "
    "rather than guesses; the product tier classifies every real catalog row and keeps "
    "premium out of bulk; a code is never reserved twice; the lanes refuse an unclaimed code"
)

_BASE_QUERY = "https://redeem.tcg.pokemon.com/en-us?2d_code="
# The older shape C1 recorded, which cards printed against it still carry.
_BASE_FRAGMENT = "https://tcg.pokemon.com/en-us/tcgl/#redeem?2d_code="

# Deliberately NOT the printed alphabet's full range: every generated code below is built
# from this and then checked for shape, so a literal in this file never matches the
# commit-time opsec rule by accident. The codes are synthetic and worthless either way.
_ALPHA = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"

# THE TWO LITERAL PLACEHOLDERS BELOW ARE LETTERS-ONLY, AND THAT IS THE OPSEC RULE RATHER THAN
# a stylistic choice. `scripts/githooks/pre-commit` blocks any 3-4-3-3 string that mixes
# letters AND digits with no repeated group, because that is what a live code looks like and
# it cannot tell a crafted placeholder from a real one. A first draft of this file used
# `ABC` + digits and would have blocked its own commit. Letters-only is one of the three
# shapes the guard deliberately passes; `AAA-1111-AAA-111` (a repeated group) is another.


def _a_code(rng) -> str:
    group = lambda n: "".join(rng.choice(_ALPHA) for _ in range(n))  # noqa: E731
    return f"{group(3)}-{group(4)}-{group(3)}-{group(3)}"


def _frame(payload: str, card_fraction: float = 0.75, blank: bool = False):
    """One rig-realistic 4K frame, built from the physical card's own geometry.

    3840x2160 because that is what `app/src/useCamera.ts` asks the camera for, and the frame
    SIZE is load-bearing rather than incidental: the first version of this decoder was chosen
    on a benchmark of 1600 px frames and the choice reversed completely when it was re-run at
    the rig's real resolution.
    """
    from PIL import Image, ImageDraw
    import numpy as np
    import zxingcpp

    height = 2160
    frame = Image.new("L", (3840, height), 150)
    if blank:
        return frame.convert("RGB")
    card_h = int(height * card_fraction)
    card_w = int(card_h * 63 / 88)
    card = Image.new("L", (card_w, card_h), 238)
    ImageDraw.Draw(card).rectangle(
        [0, 0, card_w - 1, card_h - 1], outline=90, width=max(1, card_w // 200)
    )
    symbol = Image.fromarray(
        np.array(zxingcpp.write_barcode(zxingcpp.BarcodeFormat.QRCode, payload))
    ).convert("L")
    # A ~1 cm QR on a 63 mm card is 16% of the card's width.
    side = max(8, int(card_w * 0.16))
    card.paste(symbol.resize((side, side), Image.LANCZOS), (int(card_w * 0.10), int(card_h * 0.74)))
    frame.paste(card, ((3840 - card_w) // 2, (height - card_h) // 2))
    return frame.convert("RGB")


def run() -> Result:
    from codes import ledger, products, qr
    from codes import scan as codescan

    c = Checks()
    rng = random.Random(2026)

    # ------------------------------------------------------------------ 1. the decoder
    codes = [_a_code(rng) for _ in range(8)]
    decoded = 0
    misreads = 0
    corners_seen = 0
    for code in codes:
        payload = _BASE_QUERY + code
        read = qr.decode_image(_frame(payload))
        if read is None:
            continue
        decoded += 1
        if read.code != code:
            misreads += 1
        if len(read.corners) == 4:
            corners_seen += 1
    c.equal(decoded, len(codes), "every rig-realistic frame decodes")
    c.equal(misreads, 0, "and NOT ONE of them decodes to the wrong code — the number that matters")
    c.equal(corners_seen, decoded, "each read carries C2's four fiducial corners")

    # A small card is the case the `upscale2x` rung exists for, and the guard that used to
    # switch it off on exactly this frame is the bug this check pins.
    small = qr.decode_image(_frame(_BASE_QUERY + codes[0], card_fraction=0.25))
    c.ok(
        small is not None and small.code == codes[0],
        "a card filling a QUARTER of the frame still reads — the rung guard that once "
        "disabled `upscale2x` on 4K frames is what this pins",
        f"read {small!r}",
    )

    c.equal(qr.decode_image(_frame("", blank=True)), None,
            "a frame with no QR REFUSES rather than guessing (the fork's hard rule)")

    # Both payload shapes, because cards printed against either are in circulation.
    c.equal(qr.code_from_payload(_BASE_QUERY + "ABC-DEFG-HIJ-KLM"), "ABC-DEFG-HIJ-KLM",
            "the live query-string payload yields its code")
    c.equal(qr.code_from_payload(_BASE_FRAGMENT + "abc-defg-hij-klm"), "ABC-DEFG-HIJ-KLM",
            "the older fragment payload yields the same code, upper-cased")
    c.equal(qr.code_from_payload("https://example.com/nothing"), None,
            "a QR that is not a redemption URL yields NO code rather than a substring")

    # ------------------------------------------------------------ 2. the product tier
    import csv

    export = Path("fixtures/pokemon_wide_export_untouched.csv")
    with open(export, newline="", encoding="utf-8-sig") as handle:
        rows = [
            row for row in csv.DictReader(handle)
            if (row.get("Rarity") or "").strip() == "Code Card"
            and (row.get("Condition") or "").strip() == "Near Mint"
        ]
    c.ok(len(rows) >= 40, "the fixture carries a real code-card catalog to classify against",
         f"{len(rows)} Near Mint code-card rows")
    unknown = [r["Product Name"] for r in rows if products.classify(r["Product Name"]) == products.UNKNOWN]
    c.ok(len(unknown) <= 1,
         "every real catalog product but at most one classifies to a named tier",
         f"unclassified: {unknown}")

    # THE BUG THIS PINS COST REAL MONEY IF SHIPPED. "Premium Checklane Blister" lists at
    # $0.06-$0.15 and matched the PREMIUM tier on the word "premium" alone, promoting a cheap
    # blister into the population the whole business plan exists to single out.
    c.equal(products.classify("Code Card - Stellar Crown Premium Checklane Blister [Koraidon]"),
            "blister", "a Premium Checklane Blister is a BLISTER, not a premium collection")
    c.equal(products.classify("Code Card - Prismatic Evolutions Super-Premium Collection"),
            "premium_collection", "a Super-Premium Collection is premium")
    c.equal(products.classify("Code Card - Stellar Crown Pokemon Center Elite Trainer Box (Exclusive)"),
            "pc_etb", "a Pokemon Center ETB is its own tier, not a plain ETB")
    c.equal(products.classify("Code Card - Crown Zenith Elite Trainer Box"), "etb",
            "and a plain ETB is a plain ETB")
    c.ok(products.is_premium("pc_etb") and not products.is_premium("booster"),
         "the tier flag separates the ~46x populations C11 turns on")

    # ------------------------------------------------------------------- 3. the ledger
    a, b, _d = _a_code(rng), _a_code(rng), _a_code(rng)
    entries, counts = ledger.merge([], [
        ledger.Entry(code=a, box=9, index=1, product="booster"),
        ledger.Entry(code=b, box=9, index=2, product="pc_etb"),
    ])
    c.equal(counts["new"], 2, "two fresh codes are two new ledger lines")

    entries, counts = ledger.merge(entries, [ledger.Entry(code=a, box=9, index=1, set_hint="PRE")])
    c.equal((counts["updated"], counts["new"]), (1, 0),
            "a re-scan of the SAME card at the SAME position updates in place — re-running "
            "a scan is idempotent")

    entries, counts = ledger.merge(entries, [ledger.Entry(code=a, box=12, index=4, photo="p.jpg")])
    c.equal(counts["duplicate"], 1,
            "the SAME code at a DIFFERENT position is recorded as a duplicate, never merged "
            "away — it may mean two cards bearing one code, one of which is worthless")
    c.equal(len([e for e in entries if e.code == a]), 1,
            "and it stays ONE entry, because the code is the identity")

    ledger.reserve(entries, a, order_id="order-1", buyer="somebody")
    c.equal([e.state for e in entries if e.code == a], [ledger.RESERVED],
            "reserving a code moves it out of stock")
    c.raises(ledger.CodeNotHeld, lambda: ledger.reserve(entries, a, order_id="order-2"),
             "AND A SECOND RESERVATION IS REFUSED — the one refusal that stops a code being "
             "sold twice, which the fork calls unrecoverable")

    masked = None
    try:
        ledger.reserve(entries, a, order_id="order-3")
    except ledger.CodeNotHeld as exc:
        masked = str(exc)
    c.ok(masked is not None and a not in masked,
         "and the refusal MASKS the code — an exception string reaches logs and bug reports",
         f"message was {masked!r}")

    c.raises(ledger.LedgerError,
             lambda: ledger.take(entries, order_id="big", count=99),
             "an over-large take reserves NOTHING rather than filling what it can")
    c.equal([e.state for e in entries if e.code == b], [ledger.HELD],
            "and the codes it would have taken are untouched")

    ledger.deliver(entries, a)
    ledger.kill(entries, a, "buyer_disputed")
    c.equal([e.state for e in entries if e.code == a], [ledger.DEAD],
            "a delivered code can still be marked dead — C6's replace-don't-refund is the "
            "commonest real path to that state")

    _, counts = ledger.merge(entries, [ledger.Entry(code=a, box=9, index=1)])
    c.equal(counts["terminal_skipped"], 1,
            "and re-scanning it NEVER returns it to stock")

    # ------------------------------------------------------- 4. the seam, end to end
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        caps = root / "captures" / "cards" / "box9"
        caps.mkdir(parents=True)
        written = [_a_code(rng) for _ in range(3)]
        for nth, code in enumerate(written, start=1):
            _frame(_BASE_QUERY + code).save(caps / f"{nth:04d}.jpg", "JPEG", quality=88)
            (caps / f"{nth:04d}.json").write_text(json.dumps({
                "box": 9, "index": nth, "game": "pokemon_code",
                "product": "pc_etb" if nth == 1 else "booster",
            }))
        # A fourth card with no product claim at all, which must reach NEITHER lane.
        unclaimed_code = _a_code(rng)
        _frame(_BASE_QUERY + unclaimed_code).save(caps / "0004.jpg", "JPEG", quality=88)
        (caps / "0004.json").write_text(json.dumps({"box": 9, "index": 4, "game": "pokemon_code"}))
        # And a Pokemon single, which must be left entirely alone (D21: mixed boxes are legal).
        _frame("", blank=True).save(caps / "0005.jpg", "JPEG", quality=88)
        (caps / "0005.json").write_text(json.dumps({"box": 9, "index": 5, "game": "pokemon"}))

        reading = codescan.read_directory(caps, box=9)
        c.equal(reading.photographs, 5, "the scan sees every photograph in the directory")
        c.equal(reading.code_cards, 4,
                "but reads only the code cards — a Pokemon single in a code box is left alone")
        c.equal(len(reading.entries), 4, "and decodes all four")
        c.equal(sorted(e.code for e in reading.entries),
                sorted(written + [unclaimed_code]),
                "each entry carries the code that was actually printed on its card")

        # The lanes, which is C11's operating rule and the quiet money mistake.
        from server import codes_routes

        pool_bulk = codes_routes._pool(reading.entries, codes_routes.LANE_BULK, None)
        pool_prem = codes_routes._pool(reading.entries, codes_routes.LANE_PREMIUM, None)
        c.equal(sorted(e.product for e in pool_prem), ["pc_etb"],
                "the premium lane takes the premium code and only it")
        c.equal(sorted(e.product for e in pool_bulk), ["booster", "booster"],
                "the bulk lane takes the boosters and only them")
        c.ok(all(e.code != unclaimed_code for e in pool_bulk + pool_prem),
             "AND THE UNCLAIMED CODE REACHES NEITHER LANE. Treating it as a booster would be "
             "right most of the time, which is exactly the problem: the times it is wrong a "
             "premium code leaves in a penny lot and nobody ever finds out")

    # -------------------------------------------------------------- 5. the lot builder
    from codes import lots

    lot_codes = [_a_code(rng) for _ in range(9)]
    stock = [
        # box 20: six boosters — a clean, wholly-sellable bulk box.
        ledger.Entry(code=lot_codes[0], box=20, index=1, product="booster", set_hint="PRE"),
        ledger.Entry(code=lot_codes[1], box=20, index=2, product="booster", set_hint="PRE"),
        ledger.Entry(code=lot_codes[2], box=20, index=3, product="booster", set_hint="PRE"),
        ledger.Entry(code=lot_codes[3], box=20, index=4, product="booster", set_hint="PRE"),
        ledger.Entry(code=lot_codes[4], box=20, index=5, product="booster", set_hint="PRE"),
        ledger.Entry(code=lot_codes[5], box=20, index=6, product="booster", set_hint="PRE"),
        # box 21: five boosters PLUS the three kinds of stray that would ride along in a
        # parcel. Each is a different class and each was a real defect at some point.
        ledger.Entry(code=lot_codes[6], box=21, index=1, product="booster"),
        ledger.Entry(code=lot_codes[7], box=21, index=2, product="pc_etb"),   # premium
        ledger.Entry(code=lot_codes[8], box=21, index=3),                      # no claim
    ]

    plan_entries, summary = lots.plan(
        stock, scope=lots.SCOPE_BOX, delivery=lots.DELIVERY_PHYSICAL, box=20
    )
    c.equal(summary["count"], 6, "a clean box plans as the whole box")
    c.equal(summary["premium_in_lot"], 0, "and a bulk lot carries no premium code")

    c.raises(
        lots.LotError,
        lambda: lots.plan(stock, scope=lots.SCOPE_COUNT, count=3,
                          delivery=lots.DELIVERY_PHYSICAL),
        "a PHYSICAL lot chosen by COUNT is refused — the codes reserved and the cards "
        "pulled off the shelf would be two different piles",
    )

    # THE BUG THIS PINS WAS FOUND BY READING A GENERATED PACKING SLIP. A box of 1,003 cards
    # produced a 1,000-code lot and a slip reading "Box 12, 1000 card(s)"; every filter had
    # worked, and the operator handed that slip and that box ships 1,003 — two of the three
    # strays listing at ~46x a booster.
    stray = c.raises(
        lots.LotError,
        lambda: lots.plan(stock, scope=lots.SCOPE_BOX, delivery=lots.DELIVERY_PHYSICAL,
                          box=21),
        "a box holding cards the lot would NOT take refuses outright, because 'pull box 21' "
        "would ship them anyway",
    )
    message = str(stray or "")
    c.ok("2 (" in message and "3 (" in message,
         "and the refusal names the PREMIUM stray AND the unclaimed one — the second was "
         "invisible to a first version that asked what was sellable rather than what was "
         "physically in the box",
         f"message was {message!r}")

    # A reserved-elsewhere card is the third class, and it would be shipped to two buyers.
    stock[6].state = ledger.RESERVED
    stock[6].order_id = "some-other-lot"
    other = c.raises(
        lots.LotError,
        lambda: lots.plan(stock, scope=lots.SCOPE_BOX, delivery=lots.DELIVERY_PHYSICAL,
                          box=21),
        "a card already reserved to ANOTHER lot also blocks the box",
    )
    c.ok("some-other-lot" in str(other or ""),
         "and the refusal says which lot already owns it",
         f"message was {str(other or '')!r}")

    # A DIGITAL lot has nothing to pull, so the whole-box rule does not apply to it.
    digital, _ = lots.plan(stock, scope=lots.SCOPE_COUNT, count=2,
                           delivery=lots.DELIVERY_DIGITAL)
    c.equal(len(digital), 2,
            "a DIGITAL lot may be chosen by count — nothing is pulled, so nothing can be "
            "pulled wrongly")

    built = lots.build(stock, lot_id="t8-lot", scope=lots.SCOPE_BOX,
                       delivery=lots.DELIVERY_PHYSICAL, venue="ebay", box=20)
    c.equal(built.count, 6, "building the clean box takes all six")
    c.equal(sorted(e.state for e in stock if e.box == 20),
            [ledger.RESERVED] * 6,
            "and every one of them is reserved — atomically, by the same guard that stops "
            "a code being sold twice")
    c.equal(lots.manifest_text(built).strip().splitlines(), built.codes,
            "the manifest is exactly the lot's codes, one per line and nothing else — it "
            "is pasted whole to a buyer, so anything that is not a code is work for them")
    slip = lots.packing_text(built)
    c.ok("THE WHOLE BOX" in slip and "Box 20" in slip,
         "and the packing slip says to pull the whole box, which the check above is what "
         "makes true")

    return c.result()
