/* The shape of `make demo-record`'s recording, for a checkout that has not made one.
 *
 * WHY THIS FILE EXISTS. `app/demo/bundle.json` is generated by `make demo-record` and
 * gitignored — it has never been tracked, and nothing guarantees it exists. `demoServer.ts`
 * imported it statically, so `tsc --noEmit` needed a build artefact to typecheck, and
 * `make check` therefore FAILED IN EVERY FRESH CHECKOUT, main included. It went unnoticed for
 * 121 commits because the only tree anyone ran it in happened to have made a recording.
 *
 * The runtime never reaches here: `demoServer.ts` is behind a `VITE_DEMO=1` dynamic import
 * that Rollup eliminates from an ordinary build, and the demo build seeds and records before
 * it compiles, so the real file is always present when it is actually loaded. This is the
 * TYPE, and only the type.
 *
 * IT IS DELIBERATELY THE NARROWEST SHAPE THE CONSUMER USES, so it cannot quietly stand in for
 * the real recording. `responses` is the one key `demoServer.ts` reads; the recording also
 * carries `photos`, `routes` and `wire`, and reaching for one of those against this stub is a
 * typecheck error rather than a silent `any`. When the real file IS present the alias resolves
 * to it first and the inferred type is the real one, so this weakens nothing.
 */

export default { responses: {} as Record<string, { status: number; body: unknown }> }
