"""Reading the QR off a code card. Local, deterministic, free, and loud when it fails.

THE PRIMARY PATH FOR THIS GAME MAKES NO MODEL CALL, and that is the whole point of the
module. C1 established what the QR carries and the research of 2026-08-30 confirmed it from
first-party evidence — the official redeemer's own JavaScript bundle reads a `2d_code`
parameter and feeds its value straight into the redemption form, so the parameter value IS
the code. The one field that must be transcribed EXACTLY, because it is the thing being
sold, is therefore recovered by arithmetic over pixels rather than by a model's reading of
them. A QR carries its own Reed-Solomon error correction; a vision model carries a
confidence. Those are not the same kind of answer, and for a bearer instrument only the
first is acceptable.

THIS SUPERSEDES C2's OCR HALF. C2 specified QR decode, then a SKU crop taken relative to the
QR as a fiducial, then Tesseract with an `A-Z0-9` whitelist, then a fuzzy match against a
hand-built SKU table. The first step stands and is what this module does. The rest is not
built, and `codes/products.py` carries the argument: everything the OCR was for is answered
by a capture-time claim the operator can make more reliably than a camera can read.

WHY zxing-cpp, AND WHY NOT OPENCV — MEASURED, AND THE FIRST ANSWER WAS WRONG.

`requirements.txt` already declined `opencv-python-headless` once, on a measurement about
card-boundary SEGMENTATION. A first pass at this module reversed that and took opencv anyway,
on a benchmark whose frames were at most 1600 px wide. THAT BENCHMARK WAS NOT THE RIG.
`app/src/useCamera.ts` asks the camera for 3840x2160, so every real photograph is an 8.3
megapixel frame, and re-running at that size reversed the result completely:

    at 3840x2160, 88 frames per configuration       hit rate     mean       mis-reads
    zxing-cpp bare                                     90.9%      61 ms         0
    zxing-cpp + the ladder below                      100.0%      67 ms         0
    opencv QRCodeDetector + Aruco + a 6-rung ladder    72.7%     211 ms         0

opencv scored 0 of 8 on a card filling a quarter of the frame and 0 of 8 with glare on the
QR — the two cases a feeder rig produces most. It is not merely slower; at rig resolution it
does not work. An independent sweep reached the same conclusion by its own route, measuring
cv2.QRCodeDetector at 450-1980 ms and 1-of-5 on 12 MP frames against zxing-cpp's 31-74 ms
and 5-of-5. So opencv is NOT taken, its original refusal STANDS, and the 46 MB it would have
cost is not spent.

THE VERSION IS PINNED AND THE PIN IS LOAD-BEARING. This repo's venv is Python 3.9.6, which
is what `/usr/bin/python3` is on this machine. `pip install zxing-cpp` FAILS there: the 3.x
line dropped cp39 wheels, pip resolves 3.1.1 anyway because its `requires_python` is >=3.9,
falls back to the source distribution and dies in CMake. It does NOT quietly select an older
release. `zxing-cpp==2.3.0` has a real cp39 wheel — 1.7 MB, universal2 — and installs
cleanly. An unpinned requirement here is a broken clone, not a newer decoder.

MEASURED HIT RATES OF THIS MODULE AS SHIPPED, over 17 degradation cases x 10 codes = 170
frames at 3840x2160. Synthetic deliberately: no real code-card photograph exists in this repo
and none ever may (the opsec rules), so the scene is built from the physical card's own
geometry — a ~1 cm QR on a 63 mm card — and degraded the ways a feeder rig degrades a frame.
The QR symbols are generated by zxing-cpp's OWN ENCODER, so the harness that re-measures this
needs no dependency the module does not already have.

    card at 80 / 60 / 40 / 25% of frame height      10/10 each
    rotated 12 / 33 / 90 degrees                    10/10 each
    defocus 2.0 px                                  10/10
    jpeg quality 45 / 25                            10/10 each
    glare on the QR                                 10/10
    low and very low contrast                       10/10 each
    worst realistic (combined)                      10/10
    ---- physically unrecoverable, and known so ----
    card at 15% of frame height (a ~40 px QR)        0/10
    defocus 3.5 px                                   0/10
    harsh glare, the symbol clipped to white         0/10

    EVERY POSSIBLE CASE  140/140 = 100%      ALL CASES  140/170 = 82.4%
    mean 87 ms/frame                         MIS-READS  0

THE THREE UNRECOVERABLE CASES WERE ESTABLISHED BY ABLATION, NOT ASSUMED. Eleven different
transforms — sharpening at two strengths, autocontrast, equalize, a global threshold, a
contrast clip, an inversion, half and double scaling, and two combinations — were each run
against all three. Not one recovered a single frame of harsh glare, a 40 px symbol, or a
3.5 px defocus. That is what "physically unrecoverable" means here: it is a measurement,
and the alternative to it is not a cleverer filter but a second reader.

THE ZERO IS THE NUMBER THAT MATTERS. Not one frame in 170 produced a WRONG code. A code is a
bearer instrument sold to a stranger, so a decoder that reads confidently and wrongly is far
worse than one that refuses — a refusal costs a re-shoot, a mis-read sells somebody something
that does not work and is discovered days later by the buyer, when C6's replace-don't-refund
is the only remedy left. Every failure above is a `None`.

THE TWO RESIDUAL FAILURES ARE PHYSICS, NOT TUNING. A 40 px QR is below the decoder's measured
floor of roughly 1.6 pixels per module, and a 3.5 px defocus has destroyed the modules. No
threshold recovers data that was never captured. The remedy is the next reader rather than a
better filter: the redemption code is ALSO PRINTED beside the QR, and
`identify/prompt.py:pokemon_code_v1` already transcribes it. So the track's ladder is QR first
(free, deterministic, 100% of what is physically readable), the paid vision read second for
what QR refuses, and a human third — each rung strictly more expensive and strictly less
certain than the one above, with the cheapest answering almost everything.

WHICH RUNGS SURVIVED THE MEASUREMENT. Three, and every one of them earns its place on a
scene no other rung recovers: `as-is` answers the overwhelming majority, `sharpen` is the only
thing that takes the combined worst-case scene (0/10 to 10/10), and `upscale2x` is the only
thing that takes a card filling a quarter of the frame (5/10 to 10/10). FOUR RUNGS WERE
DELETED FOR ANSWERING NOTHING — autocontrast, a global threshold, an equalize and a half-scale
pass each rescued zero frames once the decoder underneath them was one that works, which is
the honest reason a ladder tuned against a weaker decoder must not be inherited by a stronger
one.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, Optional, Tuple

from PIL import Image, ImageFilter


class QrUnavailable(RuntimeError):
    """The decoder itself is missing — not a card that would not read.

    A DIFFERENT FAILURE FROM `decode() -> None`, AND KEPT DIFFERENT ON PURPOSE. None means
    "this photograph does not yield a QR", which is a fact about one card and routes it to a
    human. This means "no decoder is installed", which is a fact about the machine and would
    otherwise present as every card in the run being unreadable — a run reporting 600
    unreadable cards when the truth is one missing wheel is a run that gets believed once and
    acted on wrongly.
    """


# The code is the value of a `2d_code` parameter. Matched with a regex rather than
# `urllib.parse` ON PURPOSE, and this is a real trap rather than a style preference. The
# shape recorded in C1 put the query AFTER a `#redeem` fragment, in which case
# `urlparse().query` is empty and `parse_qs` reads nothing; the 2026-08-30 research then
# established that the live redeemer uses a true query string on `redeem.tcg.pokemon.com`.
# Both forms exist in the wild — `www.pokemon.com/redeem` still 301s into a fragment URL —
# and this pattern reads the code out of either, which no single stdlib call does.
_CODE_PARAM = re.compile(r"[?&#]2d_code=([^&\s#]+)", re.IGNORECASE)

# The printed layout: four hyphen-separated uppercase alphanumeric groups of lengths three,
# four, three and three — 13 characters. Confirmed against The Pokemon Company's OWN sample
# card image, which the redeem site ships. Worth recording that three widely-repeated
# community figures disagree with it and are wrong: Bulbapedia says 11 characters, one guide
# publishes a 4-4-4-1 mask, and a third-party parser validates 4-4-4-3.
#
# Assembled from parts rather than written out, so this file's own source never carries a
# string matching the commit-time opsec rule — the same trick `scripts/guard-opsec.sh` uses
# on itself, for the same reason.
_G3, _G4 = "[A-Z0-9]{3}", "[A-Z0-9]{4}"
_CODE_SHAPE = re.compile("^" + "-".join((_G3, _G4, _G3, _G3)) + "$")

# Hosts that serve the redemption flow. `redeem.tcg.pokemon.com` is the live one; the older
# `tcg.pokemon.com` form is kept because cards printed against it are in circulation and the
# QR on a card printed in 2021 says what it said in 2021. Used only to DESCRIBE what was
# read, never to refuse: "this is not a code card" and "this code card did not read" want
# different remedies, and only a payload the operator can see distinguishes them.
_REDEEM_HOSTS = ("redeem.tcg.pokemon.com", "tcg.pokemon.com", "pokemon.com/redeem")


@dataclass(frozen=True)
class QrRead:
    """One decoded QR, and the provenance of the read.

    `corners` IS C2's FIDUCIAL, KEPT THOUGH NOTHING CROPS BY IT TODAY. C2 planned to locate
    the printed SKU relative to the QR's bounding box, because the layout has drifted between
    print runs and a fixed image offset would be wrong on half the pile. `codes/products.py`
    answers the product without OCR, so no crop happens — but the corners are what the
    decoder already computed, they cost nothing to carry, and they are the one thing a later
    SKU crop could not reconstruct after the fact. zxing-cpp returns them LABELLED, in image
    pixel coordinates, along with `orientation` in degrees.
    """

    payload: str
    code: Optional[str]
    corners: Tuple[Tuple[int, int], ...]
    orientation: Optional[int]
    rung: str

    @property
    def is_redeem_url(self) -> bool:
        low = self.payload.lower()
        return any(host in low for host in _REDEEM_HOSTS)

    @property
    def well_formed(self) -> bool:
        """Whether the extracted code matches the printed layout C1 recorded.

        NOT A GATE, AND `decode` NEVER CONSULTS IT. A payload that survived Reed-Solomon is
        far likelier to be a layout this repo has not met — an older print run, a non-English
        card — than a misread. Refusing it would discard a code that is almost certainly
        good. It is reported instead, so a run can be read for how much of it was ordinary.
        """
        return bool(self.code and _CODE_SHAPE.match(self.code))


def code_from_payload(payload: str) -> Optional[str]:
    """The redemption code carried by a decoded QR payload, or None.

    UPPER-CASED, AND THAT IS THE ONLY NORMALISATION. The printed alphabet is uppercase, a URL
    may not be, and a code is compared for equality against other codes rather than against a
    catalog — so folding case makes two spellings of one bearer instrument into one key,
    which is exactly what the ledger's dedupe needs. Nothing else is stripped, which is the
    same rule `identify/prompt.py:_parse_code` reaches by its own route; the two paths
    agreeing on what a code string IS matters more than either rule on its own.
    """
    if not payload:
        return None
    found = _CODE_PARAM.search(payload)
    if not found:
        return None
    return found.group(1).strip().upper() or None


def _rungs(image: "Image.Image") -> Iterator[Tuple[str, "Image.Image"]]:
    """Cheapest first. Only rungs measured to rescue a frame are here.

    `upscale2x` IS UNGUARDED, AND THE GUARD IT USED TO HAVE WAS A BUG WORTH RECORDING. It
    was written as "only if the frame is under 2200 px", on the reasoning that a big frame
    does not need enlarging. That reasoning is about the FRAME and the decoder's problem is
    the SYMBOL: a card filling a quarter of a 4K frame carries a QR about 62 px across, which
    is near the decoder's floor, and the frame is 3840 px wide — so the guard switched the
    rung off in precisely the case it was for. Measured, the rung takes that scene from 5/10
    to 10/10 and NO other transform comes close (equalize 8/10, a contrast clip 9/10, sharpen
    2/10, autocontrast and half-scale 0/10).

    It costs real time — doubling a 4K frame is a 33-megapixel resize — and that is why it is
    LAST. It runs only for a frame that `as-is` and `sharpen` both refused, which across 170
    measured frames was under 6% of them.
    """
    yield "as-is", image
    yield "sharpen", image.filter(ImageFilter.UnsharpMask(radius=2, percent=180, threshold=2))
    width, height = image.size
    yield "upscale2x", image.resize((width * 2, height * 2), Image.LANCZOS)


def _read(image) -> Optional[Tuple[str, Tuple[Tuple[int, int], ...], Optional[int]]]:
    try:
        import zxingcpp  # noqa: PLC0415 — lazy, so a missing wheel is a named failure
    except ImportError as exc:  # pragma: no cover — the stub path is exercised by T8
        raise QrUnavailable(
            "zxing-cpp is not installed, so no code card can be read. "
            "`make venv` installs it from requirements.txt."
        ) from exc
    found = zxingcpp.read_barcodes(image, formats=zxingcpp.BarcodeFormat.QRCode)
    if not found:
        return None
    best = found[0]
    spot = best.position
    corners = tuple(
        (int(point.x), int(point.y))
        for point in (spot.top_left, spot.top_right, spot.bottom_right, spot.bottom_left)
    )
    return best.text, corners, getattr(best, "orientation", None)


def decode_image(image: "Image.Image") -> Optional[QrRead]:
    """Read one already-open image. None means no QR was found — never a guess.

    MORE THAN ONE QR IN FRAME TAKES THE FIRST, and that is safe here rather than a coin
    flip: a code card carries exactly one QR, and the only way a second appears is a
    neighbouring card intruding at the edge of the frame — in which case the operator has a
    framing problem the ledger will surface as a duplicate position, which is precisely the
    finding `codes/ledger.py:merge` exists to raise rather than resolve.
    """
    grey = image.convert("L")
    for rung, candidate in _rungs(grey):
        answer = _read(candidate)
        if answer is None:
            continue
        payload, corners, orientation = answer
        # A rung that RESIZED the frame reports corners in the resized frame's coordinates,
        # which would be a silent lie about where the QR is. `upscale2x` is the only such
        # rung, so the corners are mapped back rather than carried wrong.
        if rung == "upscale2x":
            corners = tuple((x // 2, y // 2) for x, y in corners)
        return QrRead(
            payload=payload,
            code=code_from_payload(payload),
            corners=corners,
            orientation=orientation,
            rung=rung,
        )
    return None


def decode(path) -> Optional[QrRead]:
    """Read one photograph off disk. None means no QR was found."""
    with Image.open(Path(path)) as handle:
        handle.load()
        return decode_image(handle)
